"""Created Location Table

Revision ID: 02ccb21412aa
Revises: ec46ad7fc181
Create Date: 2024-03-06 12:19:18.386806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ccb21412aa'
down_revision = 'ec46ad7fc181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_description'), 'location', ['description'], unique=False)
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_index(op.f('ix_location_description'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
