"""empty message

Revision ID: 6cc1a2252526
Revises: 02ccb21412aa
Create Date: 2024-03-06 12:52:11.698580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc1a2252526'
down_revision = '02ccb21412aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
