"""Create Package table

Revision ID: 77fe142abc81
Revises: b01ccb40f2b5
Create Date: 2024-03-06 23:50:51.449459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fe142abc81'
down_revision = 'b01ccb40f2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
