"""empty message

Revision ID: b01ccb40f2b5
Revises: 6cc1a2252526
Create Date: 2024-03-06 20:26:13.795527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01ccb40f2b5'
down_revision = '6cc1a2252526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
